<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/scoring.js') ?>"></script>
<script type="text/javascript">
//<![CDATA[
    var paymentCssSelector = '<?php
        $version = explode(".", Mage::getVersion());
        if($version[0]==1 && $version[1]<8){
            echo '#checkout-payment-method-load dl dt';
        }elseif ($version[0]==1 && $version[1]>=8) {
            echo '#checkout-payment-method-load dt';
        }
    ?>';
//]]>
</script>
