<ul id="scoring_solvencygroups_template" style="display: none;">
    <?php echo $this->getRowTemplateHtml() ?>
</ul>
<ul id="scoring_solvencygroups">
<?php foreach ($this->getGroups() as $id => $group): ?>
    <?php echo $this->getRowTemplateHtml($id) ?>
<?php endforeach;?>
</ul>
<script type="text/javascript">
cl = function() { return console.log.apply(console, arguments); };
    function getConfigId() {
        var existing_ids = new Array();
        $$(".solvencygroup_counter").each(function(el){
        	configId = el.previousSiblings()[0].id.replace('headline-[', '').replace(']','');
            existing_ids[configId] = true;
        });
        new_id=0;
        while (new_id < 100){
            new_id++;
            if(!existing_ids[new_id]) {
                return new_id;
            }
        }
    }

    function updateHeadline(element)
    {
        $(element.id.replace('input-name', 'headline')).innerHTML = element.value.stripTags(); 
    }
</script>
<?php echo $this->getAddRowButtonHtml(
    'scoring_solvencygroups',
    'scoring_solvencygroups_template', 
    $this->__('Add relation')
); ?>
